'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

def even_fibonacci():
    ans = 0
    b = 1
    even_count = 2
    while b <= 4000000:
        if b % 2 == 0:
            ans = ans + b
        b,even_count = even_count,b + even_count
    return str(ans)

if __name__ == "__main__":
    print(even_fibonacci());
            
    
